In [23]:
import re
import pandas as pd
import requests
import numpy as np

In [24]:
path = r"F:\Innomatics\TASK-2\GMT20240125-121850_RecordingnewChat"

In [25]:
import os
list1=[]
for i , j, k in os.walk(path):
    if len(k)>0:
        file = os.path.join(str(i)+ "\\" +str(k[0]))
        list1.append(file)
        
print(list1)

['F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_1\\GMT20240125-121850_RecordingnewChat - Copy (1).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_10\\GMT20240125-121850_RecordingnewChat - Copy (10).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_11\\GMT20240125-121850_RecordingnewChat - Copy (11).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_12\\GMT20240125-121850_RecordingnewChat - Copy (12).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_13\\GMT20240125-121850_RecordingnewChat - Copy (13).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_14\\GMT20240125-121850_RecordingnewChat - Copy (14).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_15\\GMT20240125-121850_RecordingnewChat - Copy (15).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_2\\GMT20240125-121850_RecordingnewChat - Copy (2).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_3\\GMT20240125-121850_RecordingnewChat - Copy (3).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_4\\GMT20240125-121850_RecordingnewChat - Copy (4).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_5\\GMT20240125-121850_RecordingnewChat - Copy (5).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_6\\GMT20240125-121850_RecordingnewChat - Copy (6).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_7\\GMT20240125-121850_RecordingnewChat - Copy (7).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_8\\GMT20240125-121850_RecordingnewChat - Copy (8).txt', 'F:\\Innomatics\\TASK-2\\GMT20240125-121850_RecordingnewChat\\recovery_9\\GMT20240125-121850_RecordingnewChat - Copy (9).txt']

In [26]:
finallist=[]
for i in list1:
    with open (r'{}'.format(i),"r" ,encoding = "utf-8") as txt:
        f = txt.readlines()
        finallist.append(f)

In [27]:
finallist

[['00:15:43\tHarsh Sharma:\tDiscord link\n',
  '00:19:47\tAdepu Kavya:\tyes\n',
  '00:19:47\tSai Ramya Manthri Pragada:\tyes\n',
  '00:19:47\tJai Chaudhrani:\tAudible\n',
  '00:19:47\tAdnan Baig:\tYes\n',
  '00:19:47\tNikita Bagde:\tyes\n',
  '00:19:47\tSakshi Yadav:\tyes\n',
  '00:19:47\t1RF- Surya Atrish - SIET:\tyes sir\n',
  '00:19:48\tLakshmi Teja Illuri:\taudible\n',
  '00:19:48\tArpan Ghosh:\tyes\n',
  '00:19:48\tRohit Sahu:\tyes\n',
  '00:19:48\tLavanya Varikuppala:\tAudible\n',
  '00:19:48\tKishore Reddy:\tS\n',
  '00:19:48\tSurineni Abhi:\tAudible\n',
  '00:19:49\tGaurav Bhardwaj:\taudible\n',
  '00:19:49\tSuneel Kumar:\tyes\n',
  '00:19:49\tYogapriya peethambaram:\tyes\n',
  '00:19:49\tdommeti sai lakshmi sree:\tyes\n',
  '00:19:49\tNeeraj Kumar:\tAudible\n',
  '00:19:49\tMidde Rishanth:\tYes\n',
  '00:19:49\tMd Ibrahim Ahmed:\tYess\n',
  "00:19:49\tSai Sudhane G:\tIt's audible\n",
  '00:19:50\tLashika A:\tYes sir audible\n',
  '00:19:50\tPavankalyan Janga:\tY\n',
  '00:19:50\tSoham Amipara:\tYes\n',
  '00:19:50\tKANDE RAKESH:\tYes sir\n',
  '00:19:50\tshivaramakrishna thokala:\tyes\n',
  '00:19:52\tAleena Joseph:\tyes audible\n',
  '00:19:52\tMonika:\tYES\n',
  '00:19:52\tsaurabh kor:\tBreaking\n',
  '00:19:53\tMohammed Farhan Ahmed:\tY\n',
  '00:19:53\tAbhishek Enikepalli:\tyes sir\n',
  '00:19:53\tMahesh veeraboina:\tYes\n',
  '00:19:53\tVarahala Durga:\tyes\n',
  '00:19:53\tKartik Dhanai:\tYes\n',
  '00:19:53\tAthira Kumari:\tYes\n',
  "00:19:54\tMD MOBASSIR HASSSAN:\tguys please don't drop this much msg\n",
  '00:19:54\tKavin Puri:\tAudible\n',
  '00:19:56\tVishvaas Swaminathan:\tYep\n',
  '00:19:57\tsyed sameer:\taudible\n',
  '00:19:59\tSujay Kumar:\tyes sir\n',
  '00:20:05\tSai Karteek Kompally:\tyes\n',
  '00:20:07\t1RF- Surya Atrish - SIET:\tdont raise your hands people\n',
  '00:20:12\tChirra Satish:\t👍\n',
  '00:20:15\tKOTHAKONDA GANESH:\tblank\n',
  '00:20:17\tGurram Ruthvi Chaitanya:\tno\n',
  '00:20:20\tMidde Rishanth:\tNo\n',
  '00:20:22\tShaik Mahammadrafi:\tNo\n',
  '00:20:24\tHarshit Punera:\tpublicity\n',
  '00:20:27\tNidiginti Saiprasad:\tno\n',
  '00:20:28\tDarshan Gowda M:\tskillset\n',
  '00:20:28\tVyom Modi:\tskillset\n',
  '00:20:28\tsyed sameer:\tSkill set\n',
  '00:20:29\tSai Karteek Kompally:\tskillset\n',
  '00:20:29\tLakshmi Teja Illuri:\tSkillset\n',
  '00:20:29\tRadhika Aggarwal:\tskillset\n',
  '00:20:29\tSwathi Putti:\tskill set\n',
  '00:20:29\tDivya .:\tskillset\n',
  '00:20:29\tS MANICHANDANA:\tskillset\n',
  '00:20:29\tVishakha Santosh Deshmukh:\tskillset\n',
  '00:20:29\tAkash Karale:\tskillset\n',
  '00:20:29\tDeepak kumar:\tskillset\n',
  '00:20:29\tvignesh B:\tskillset\n',
  '00:20:29\tNikhitha Chinthala:\tskill\n',
  '00:20:29\tNishitha Manikya:\tskill set\n',
  '00:20:29\tGurram Ruthvi Chaitanya:\tskill\n',
  '00:20:29\tPravalika Eleshala:\tSkill set\n',
  '00:20:29\tRakshit Gupta:\tskillset\n',
  '00:20:29\tUmamahesh Yenamala:\tSkill\n',
  '00:20:29\tKunal Pattanshetti:\tskill set\n',
  '00:20:30\tKOTHAKONDA GANESH:\tskillset\n',
  '00:20:30\tANIL DEVALLA:\tskillset\n',
  '00:20:30\tVikramadhithya Thotam:\tskill\n',
  '00:20:30\tPrerna Pal:\tSkill\n',
  '00:20:30\tMaradapu Charishma:\tskillset\n',
  '00:20:30\tSoumen Mondal:\tskillset\n',
  '00:20:30\tAzhakudurai K:\tskill\n',
  '00:20:30\tManda Divija:\tskill set\n',
  '00:20:30\tOm Gori:\tskillset\n',
  '00:20:30\tMohammed Farhan Ahmed:\tTool\n',
  '00:20:30\tHridya Shree R:\tskillset\n',
  '00:20:30\tSai Sudhane G:\tSkillset\n',
  '00:20:31\tKrishna Kumar:\tSkillset\n',
  '00:20:31\tDeep Lathiya:\tskill set\n',
  '00:20:31\tSRK Teja Nidumukkala:\tskillset\n',
  '00:20:31\tKartik Dhanai:\tSkill set\n',
  '00:20:31\tManaswini Deshpande:\tskill\n',
  '00:20:31\tAnushka Yeole:\tskills set\n',
  '00:20:31\tSakshi Yadav:\tskillset\n',
  '00:20:31\tLavanya Varikuppala:\tSkill\n',
  '00:20:31\tSpoorti Ramtirth:\tskillset\n',
  '00:20:31\tSravya Degala:\tskillset\n',
  '00:20:31\tkrishna vamsi Naidu:\tskill set\n',
  '00:20:31\tSwastik Dubey:\tSkill\n',
  '00:20:31\tAparajita Singh:\tSkillset\n',
  '00:20:31\tSURAJ SAHU:\tskillset\n',
  '00:20:31\tVishvaas Swaminathan:\tSkill set\n',
  '00:20:31\tSunitha Devi:\tskill set\n',
  '00:20:31\tdishan shettigar:\tskillset\n',
  '00:20:31\tishaan b:\tskill\n',
  "00:20:32\tHannah Igboke:\tIt's a skillset.\n",
  '00:20:32\tJothinathan Chandrasekar:\tskillset\n',
  '00:20:32\tSowjanya Anaji:\tskillset\n',
  '00:20:32\tSohil Sharma:\tSkill\n',
  '00:20:32\tShajitha Banu Rasul Khan:\tSkillset\n',
  '00:20:32\tMd Ibrahim Ahmed:\tSkill set\n',
  '00:20:32\tPRATIK PATIDAR:\tskillset\n',
  '00:20:32\tSnehal Vispute:\tskillset\n',
  '00:20:32\tMamatha paritala:\tSKILL SET\n',
  '00:20:32\tkothapalli shiva durga prasad:\tSkillset\n',
  '00:20:32\tHarshit Punera:\tskillset\n',
  '00:20:32\tSamyukta Balaji:\tskillset\n',
  '00:20:33\tpatil gopal:\tskillset\n',
  '00:20:33\tManojkumar Chiluka:\tskill set\n',
  '00:20:33\tAjay Koka:\tskillset\n',
  '00:20:33\tShubham Jadhav:\tskill\n',
  '00:20:33\tNandini Kokare:\tskillset\n',
  '00:20:33\tAleem Shaik:\tskillset\n',
  '00:20:33\tGarimella Aparna Devi:\tskillset\n',
  '00:20:33\tArun kumar Vollala:\tskillset\n',
  '00:20:33\tAishwary Dakhare:\tskillset\n',
  '00:20:33\tSandhya Rani:\tskillset\n',
  '00:20:33\tKritagyay Upadhayay:\tskillset\n',
  '00:20:33\tHemanth Goli:\tskillset\n',
  '00:20:33\tSujay Kumar:\tskillset\n',
  '00:20:33\tTarun Kummari:\tskillset\n',
  '00:20:33\tMohammed Gufran:\tskill set\n',
  '00:20:33\tRavi Panchireddy:\tskillset\n',
  '00:20:34\tNaga Durga Sai Peyyala:\tskillset\n',
  '00:20:34\tRelangi kavya Sri:\tskillset\n',
  '00:20:34\tRizwana Yasmeen:\tskillset\n',
  '00:20:34\tNithin Katukoori:\tmarketing is a skillset\n',
  '00:20:34\tArun Kumar Sahu:\tskill\n',
  '00:20:34\tManoj Yadav:\tskillset\n',
  '00:20:34\tNithya Sri:\tskillset\n',
  '00:20:34\tChervolo RAM MOHAN:\tSkill\n',
  '00:20:34\tYogapriya peethambaram:\tskillset\n',
  '00:20:34\tChennareddy Pranavi Reddy:\tskillset\n',
  '00:20:34\tNidiginti Saiprasad:\tskill set\n',
  '00:20:34\tMuthoju Amulya:\tskillset\n',
  '00:20:34\tsuhan reddy paidi:\tskillset\n',
  '00:20:34\tRutuja Dhavale:\tSkillset\n',
  '00:20:34\tPatlolla Pranavkumar:\tskill\n',
  '00:20:34\tSingireddy Pravalika:\tskill set\n',
  '00:20:34\tBiradar Shashikanth:\tskillset\n',
  '00:20:34\tShreya Sanap:\tSkillset\n',
  '00:20:34\tPRASHANTH E:\tSkill set\n',
  '00:20:34\tKeerthana Potturi:\tskill set\n',
  '00:20:34\tANURASHMI DALAI:\tskillset\n',
  '00:20:34\tLashika A:\tskillset\n',
  '00:20:35\tNeeraj kumar:\tskillset\n',
  '00:20:35\tbunty_IN1240278:\tSkillset\n',
  '00:20:35\tBodempudi Bhavya:\tskill\n',
  '00:20:35\tAdnan Baig:\tskillset\n',
  '00:20:35\tTalla Bhavani:\tSkillset\n',
  '00:20:35\tNikita Bagde:\tskillset\n',
  '00:20:35\tShrikant Suryawanshi:\tSkillset\n',
  '00:20:35\tSurineni Abhi:\tSkill set\n',
  '00:20:35\tMOHAMMAD TOKEER QUARIASHI:\tskillset\n',
  '00:20:35\tPavan Kumar Reddy Banavasi:\tskillset\n',
  '00:20:35\tPruthviraj Pallykonda:\tskillset\n',
  '00:20:36\tChetan Jadhav:\tSkill set\n',
  '00:20:36\tSuresh Bommeraboina:\tSkill set\n',
  '00:20:36\tBhagyasree Guthula:\tskill set\n',
  '00:20:36\tAdepu Kavya:\tskillset\n',
  '00:20:36\tKushal Adhyaru:\tskill\n',
  '00:20:36\tBishal Pal:\tskillset\n',
  '00:20:36\tSaumya Sharma:\tskill set\n',
  '00:20:36\tVarahala Durga:\tskillset\n',
  '00:20:36\tRagini Paswan:\tSkillset\n',
  '00:20:36\tS Harshitha:\tSkill set\n',
  '00:20:36\tSamyank Meshram:\tSkillset\n',
  '00:20:36\tParmati Preetham:\tSKILLSET\n',
  '00:20:37\tTashmeet Kaur Hora:\tskill set\n',
  '00:20:37\tTabassum Shaikh:\tskills\n',
  '00:20:37\tDeepa Bhatt:\tskill set\n',
  '00:20:37\tJaswanth D S:\tSkill set\n',
  '00:20:37\tHeli Pavashiya:\tskillset\n',
  '00:20:37\tVikramadhithya Thotam:\tskillset\n',
  '00:20:37\tSamiksha Balshete:\tskillset\n',
  '00:20:37\tMitrabhanu Panda:\tSkill set\n',
  '00:20:37\tSyamala Ganti:\tskill set\n',
  '00:20:37\tvaishnavi pusthakala:\tskillset\n',
  '00:20:37\tMANCHODI MADHU SAGAR:\tskillset\n',
  '00:20:37\tSumanth kasula:\tskillset\n',
  '00:20:37\tPRATIK PATIDAR:\tSkillSet\n',
  '00:20:38\tRubi Singh:\tskill set\n',
  '00:20:38\tSid Farakate:\tskillset\n',
  '00:20:38\tBADISHAGANDU RAVINDER:\tskill set\n',
  '00:20:38\tShiva Kumar:\tSkill\n',
  '00:20:38\tElagandula Manikanta:\tskill and tool\n',
  '00:20:38\tsaurabh kor:\tSkillset\n',
  '00:20:38\tDAARA ARUNRAJ:\tSkill\n',
  '00:20:38\tManisha Lokapally:\tSkillset\n',
  '00:20:38\tMonika:\tSKILL\n',
  '00:20:39\tHeenaa mohammed:\tskillset\n',
  '00:20:39\tKotha Ananthasai:\tskill\n',
  '00:20:39\tShaheem MK:\tskillset\n',
  '00:20:39\tMukku Sumanth:\tskill set\n',
  '00:20:39\tAbdul Rauf:\tSkillset\n',
  '00:20:39\tUsirikayala Anusha:\tskiilset\n',
  '00:20:39\tSowmya Sri:\tSkillset\n',
  '00:20:39\tSatyaprakash Sahoo:\tskillset\n',
  '00:20:39\tS.Dinesh Kumar:\tskillset\n',
  '00:20:39\tBharath Kodigudla:\tSkillset\n',
  '00:20:39\tJaggireddygari Dhanunjaya Reddy:\tSkillsey\n',
  '00:20:40\tAngel Mary Poulina:\tskillset\n',
  '00:20:40\tRohit Sahu:\tskillset\n',
  '00:20:40\tReshma Sk:\tskillset\n',
  '00:20:40\tRaja Sri Yayavaram:\tskillset\n',
  '00:20:40\tPavan Satya Kalyan Vaanapalli:\tSkill set\n',
  '00:20:40\tGautam Kumar Rayapudi:\tskill\n',
  '00:20:40\tlaxmi prasanna_IN1240514:\tskillset\n',
  '00:20:40\tSyed Abdul Raheem:\tSkillset\n',
  '00:20:40\tMamidipally Rajeshwari:\tSkill set\n',
  '00:20:40\tSanjana Kududula:\tskillset\n',
  '00:20:41\tAmit Jadhav:\tSkillset\n',
  '00:20:41\tDev Halvawala:\tSkill\n',
  '00:20:41\tBaddam Akshara:\tskillset\n',
  '00:20:41\tThumma Akhila:\tskillset\n',
  '00:20:41\tAzharuddin Ansari:\tSkill\n',
  '00:20:42\tPavan Kumar Nidhanapati:\tskill set\n',
  '00:20:42\tShaik Mahammadrafi:\tSkill set\n',
  '00:20:42\tAbhinav Chandra:\tskillset\n',
  '00:20:42\tdommeti sai lakshmi sree:\tskill set\n',
  '00:20:43\tAminat Owodunni:\tSkillset\n',
  '00:20:43\tJisna Hameed:\tSkillset\n',
  '00:20:43\tNabilah Tabassum:\tSkillset\n',
  '00:20:43\tPavan Kumar:\tskill set\n',
  '00:20:44\tPavankalyan Janga:\tSkills\n',
  '00:20:44\tShivani Aakula:\tskillset\n',
  '00:20:44\tPavithra Subramani:\tskillset\n',
  '00:20:44\tPreethi Sundar:\tskillset\n',
  '00:20:44\tPRATIK PATIDAR:\tSkillSet\n',
  '00:20:44\tMD SAMEERA:\tskillset\n',
  '00:20:45\tMOHAMMAD TOKEER QUARIASHI:\tskillset\n',
  '00:20:45\tM Shiva Kumar:\tSkillset\n',
  '00:20:45\tTabassum Shaikh:\tyes\n',
  '00:20:45\tSai Karteek Kompally:\tyes\n',
  '00:20:45\tKritagyay Upadhayay:\tyes\n',
  '00:20:45\tPravalika Eleshala:\tyes\n',
  '00:20:45\tNaga Durga Sai Peyyala:\tyes\n',
  '00:20:46\tGarimella Aparna Devi:\ts\n',
  '00:20:46\tShreya Ranjankar:\tskillset\n',
  '00:20:46\tLakshmi Teja Illuri:\tyes\n',
  '00:20:46\tK Neha Reddy:\tskill set\n',
  '00:20:46\tSubhadra Bhupathiraju:\tSkill set\n',
  '00:20:46\tMidde Rishanth:\tYes\n',
  '00:20:46\tVishakha Santosh Deshmukh:\tyes\n',
  '00:20:46\tDeepa Bhatt:\tyes\n',
  '00:20:47\tDavid Uchenna:\tSkillset\n',
  '00:20:47\tManda Divija:\tyes\n',
  '00:20:47\tThallapalli Navyateja:\tyess\n',
  '00:20:47\tSaumya Sharma:\tyes\n',
  '00:20:47\tAnushka Yeole:\tyes\n',
  '00:20:47\tdishan shettigar:\tyes\n',
  '00:20:47\tAkash Karale:\tyes\n',
  '00:20:47\tNandini Kokare:\tyes\n',
  '00:20:48\tMOHAMMAD TOKEER QUARIASHI:\tskillset\n',
  '00:20:48\tGurram Ruthvi Chaitanya:\tyes\n',
  '00:20:48\tRadhika Aggarwal:\tyes\n',
  '00:20:48\tdommeti sai lakshmi sree:\tskill set\n',
  '00:20:48\tYashas Gupta:\tYes\n',
  '00:20:48\tbunty_IN1240278:\tYes\n',
  '00:20:48\tMonika:\tYES\n',
  '00:20:48\tNikita Bagde:\tyes\n',
  '00:20:48\tHarshit Punera:\tyes\n',
  "00:20:48\tShubham Jadhav:\tyes'\n",
  '00:20:48\tShaheem MK:\tyes\n',
  '00:20:49\tVikramadhithya Thotam:\tyes\n',
  '00:20:49\tMD SAMEERA:\tyes\n',
  '00:20:49\tKartik Dhanai:\tIt includes soft skills\n',
  '00:20:50\tNabilah Tabassum:\tYes\n',
  '00:20:50\tMegha Ahirwar:\tYes\n',
  '00:20:50\tKritagyay Upadhayay:\tyes\n',
  '00:20:51\tsaurabh kor:\tSell our product\n',
  '00:20:51\tGautam Kumar Rayapudi:\tyes\n',
  '00:20:51\tRukmini Hatkar:\tSkillset\n',
  '00:20:52\tRavi Rathod:\tSkill set\n',
  '00:20:52\tSai Sudhane G:\tYes\n',
  '00:20:52\tThumma Akhila:\tyes\n',
  "00:20:52\tShreya Ranjankar:\tyes'\n",
  '00:20:52\tManojkumar Chiluka:\tyes\n',
  '00:20:53\tAyush Raj:\tSkillset\n',
  '00:20:54\tMaradapu Charishma:\tyes\n',
  '00:20:54\tMegha Ahirwar:\tYes\n',
  '00:20:55\tAKHILA RAJA:\tYes\n',
  '00:20:56\tMahesh Babu Pentam:\tSkill set\n',
  '00:20:57\tArthi Sri Sowmya Mogulluru:\tSkillset\n',
  '00:20:57\tSohil Sharma:\tBrand\n',
  '00:20:58\tAbhishek Ganeshkar:\tI think it is skill to marketing our products or services\n',
  '00:20:59\tAbdul Nadeem Mohd:\tMarketing is the process of promoting, selling, and distributing a product or service to potential customers. It involves understanding customer needs and desires, developing products or services that fulfill those needs, pricing them appropriately, and then making them accessible to the target audience through various channels\n',
  '00:21:00\tDarshan Gowda M:\tto sell\n',
  '00:21:00\tSRK Teja Nidumukkala:\tTo standout\n',
  '00:21:00\tRutuja Dhavale:\tCommunication\n',
  '00:21:00\tVAISHNAVI SINGH:\tskillset\n',
  '00:21:01\tShraddha Kalaskar:\tProfit\n',
  '00:21:02\tSatyaprakash Sahoo:\tto sell\n',
  '00:21:03\tB Shivakrishna:\tit is orocessing of selling products\n',
  '00:21:03\tAashish Kasar:\texposer\n',
  '\n',
  'brand\n',
  '00:21:03\tPavan Kumar Reddy Banavasi:\tdatascience directly prportional to marketing\n',
  '00:21:04\tKartik Dhanai:\tTo showcase our idea\n',
  '00:21:04\tMD SAMEERA:\tpromoting\n',
  '00:21:05\tMegha Ahirwar:\tWe have to convey our solutions to the client\n',
  '00:21:05\tPRATIK PATIDAR:\tFor Publicity\n',
  '00:21:06\tMidde Rishanth:\tTo sell the product\n',
  '00:21:06\tVikramadhithya Thotam:\tto define about us\n',
  '00:21:06\tGOWRABATHINA RAKESH:\tshowcase\n',
  '00:21:06\tHemanth Goli:\tto standout\n',
  '00:21:07\tMohammed Farhan Ahmed:\tRecognition\n',
  '00:21:07\tSwastik Dubey:\tBranding\n',
  '00:21:07\tPeddinti Purushottam Sai:\tShowcase a product\n',
  '00:21:07\tkrishna vamsi Naidu:\tsales\n',
  '00:21:07\tTabassum Shaikh:\tto convey\n',
  '00:21:08\tKatiboina Shiva Kumar:\tleveraging the skills\n',
  '00:21:08\tSatyaprakash Sahoo:\tto sell\n',
  '00:21:10\tDev Halvawala:\tIt is a type of a soft skill\n',
  '00:21:11\tRelangi kavya Sri:\tto explore something\n',
  '00:21:11\tSunitha Devi:\tto sale our product\n',
  '00:21:12\tKotha Ananthasai:\tto get good package\n',
  '00:21:12\tShajitha Banu Rasul Khan:\tMarketing- strategy for finding the right people for our products\n',
  '00:21:12\tSai Sudhane G:\tThe ability to promote a thing\n',
  '00:21:12\tGurram Ruthvi Chaitanya:\tpromoting a product\n',
  '00:21:12\tishaan b:\tone must know domain knowledge\n',
  '00:21:12\tSoumen Mondal:\thow to sell\n',
  '00:21:12\tGarimella Aparna Devi:\tability to promote\n',
  '00:21:13\tShubham Prajapati:\tReaching the right audience\n',
  '00:21:13\tSurineni Abhi:\tPromoting\n',
  '00:21:13\tAnushka Yeole:\tselling ur product\n',
  '00:21:13\tSubhadra Bhupathiraju:\tShowcasing ourself\n',
  '00:21:13\tDeepak kumar:\tto show ourself\n',
  '00:21:13\tPRASHANTH E:\tHighlighting\n',
  '00:21:13\tVishvaas Swaminathan:\tMarketing is the process of promoting and selling products or services to customers. It involves strategies like advertising, branding, and market research. I\n',
  '00:21:14\tBADISHAGANDU RAVINDER:\tto promote our delf\n',
  '00:21:14\tPranav Bhawsar:\tto present yourself out performing from crowd\n',
  '00:21:14\tHarshit Punera:\tpromoting the prduct\n',
  '00:21:14\tRadhika Aggarwal:\tto promote our skills\n',
  '00:21:14\tHannah Igboke:\tMarketing is simply sales. How to sell yourself and what you do to others in order to get a job and be paid adequately for it.\n',
  '00:21:14\tSohil Sharma:\tIf a company fires you, more companies should hire you\n',
  "00:21:14\tSai Krishna Dusa:\tIt's a skillset. Marketing is the skill of getting your product known to a set of customers by using effective strategies. I imporves overall sales of a product\n",
  "00:21:15\tSai Krishna Dusa:\tIt's a skillset. Marketing is the skill of getting your product known to a set of customers by using effective strategies. I imporves overall sales of a product\n",
  '00:21:15\tManaswini Deshpande:\tpublinessc awar\n',
  "00:21:15\tSai Krishna Dusa:\tIt's a skillset. Marketing is the skill of getting your product known to a set of customers by using effective strategies. I imporves overall sales of a product\n",
  '00:21:15\tSanjana Kududula:\tto communication  and promote\n',
  '00:21:16\tMohammed Gufran:\thahahahahah\n',
  '00:21:17\tKritagyay Upadhayay:\tto sell ourselves in the market means to present our self\n',
  '00:21:17\tMahesh veeraboina:\tTo convince\n',
  '00:21:17\tSamyukta Balaji:\tMarketing is required to tell people why they should have something\n',
  '00:21:18\tNaresh Mula:\tPROMOTING A BUSINESS\n',
  '00:21:18\tVyom Modi:\tto get our profile and skillsets in it noticed by relevant people\n',
  '00:21:18\tRubi Singh:\tpresentation of product\n',
  '00:21:18\tKOTHAKONDA GANESH:\tto grow\n',
  '00:21:18\tGurram Ruthvi Chaitanya:\tpromoting\n',
  '00:21:19\tMonika:\tbecause to how you help the company to grow\n',
  '00:21:19\tSoumen Mondal:\thow to sell\n',
  '00:21:19\tNeeraj Kumar:\tIf we have the insights then where we will sell tha data\n',
  '00:21:19\tUsirikayala Anusha:\tto advertise about our knowlege\n',
  '00:21:20\tPrerna Pal:\tTo put our points and thinking properly\n',
  '00:21:20\tAjay Koka:\t😆\n',
  '00:21:20\tSowjanya Anaji:\tTo showcase our skills to fit in job\n',
  '00:21:21\tAleena Joseph:\tto showcase our talents\n',
  '00:21:21\tAzhakudurai K:\tto sell a product or ourselves\n',
  '00:21:21\tAkash Karale:\tBy marketing we can represent ourself\n',
  '00:21:21\tShubham Jadhav:\tselling brand mking etc\n',
  '00:21:22\tPavankalyan Janga:\tWe need to convince persons\n',
  '00:21:23\tJisna Hameed:\tTo showcase the skills we have\n',
  '00:21:23\tKartik Dhanai:\tTo showcase our idea\n',
  '00:21:24\tBishal Pal:\tthe ability to sell\n',
  '00:21:24\tYashas Gupta:\tPromoting ourselves\n',
  '00:21:24\tSubhayan Mahato:\tCreating a buzz in the world is known as marketing\n',
  '00:21:24\tMounika Savala:\tpromoting a new product\n',
  '00:21:24\tManojkumar Chiluka:\tto reach any product to common people\n',
  '00:21:24\tsyed sameer:\tCreating awareness on how capable you are\n',
  '00:21:24\tKranthi Sunkari:\tShowing our skills\n',
  '00:21:25\tManda Divija:\tto bring our product into market\n',
  '00:21:26\tArun Kumar Sahu:\tsale product\n',
  '00:21:28\tRagini Paswan:\tTo promote\n',
  '00:21:28\tSalikanti Karthik:\tYes in order to deliver the product we must understand the neccesities of needs of people\n',
  '00:21:28\tAashish Kasar:\t😅\n',
  '00:21:28\tGOWRABATHINA RAKESH:\tshowcase\n',
  '00:21:29\tSid Farakate:\tcreating brand image\n',
  '00:21:30\tMADHAVAN N:\tIt is a type of qualification need to sell our products\n',
  '00:21:30\tSpoorti Ramtirth:\tshowcase\n',
  '00:21:30\tSivasankar S:\tSales\n',
  '00:21:31\tDivya .:\twe should make ourselves acceptable by companies .. for that we should we should market our capabilities .\n',
  '00:21:31\tGurram Ruthvi Chaitanya:\tpromoting\n',
  '00:21:32\tChetan Jadhav:\tIntroducing ourself what is aur ability\n',
  '00:21:32\tsaurabh kor:\tTo showcas our advantages\n',
  '00:21:32\tLavanya Varikuppala:\tLetting know others what you are doing\n',
  '00:21:35\tAminat Owodunni:\tadvertising a product\n',
  '00:21:35\t1RF- Surya Atrish - SIET:\tthe ability to communicate the utility of a product/service to the clients (self answered)\n',
  '00:21:36\tPavan Kumar Reddy Banavasi:\tanalysing in data science\n',
  'and showing product with marketting\n',

In [28]:
message=[]
for i in finallist:
    for j in i:
        
        m=re.findall(':\\t(\w.+)',j)
        if(m):
            message.append(m[0])
        else:
            message.append(np.nan)

In [29]:
d1={}

d1['Message']=message
dm1=pd.DataFrame(d1)
dm1

                                                 Message
0                                           Discord link
1                                                    yes
2                                                    yes
3                                                Audible
4                                                    Yes
...                                                  ...
44811                      sir it is showing preequation
44812                             innomatics hd logo sir
44813  sir should we add experience related to other ...
44814                                   sir discord link
44815                   lms access mail not received sir

[44816 rows x 1 columns]

In [30]:
dm1['Message'].value_counts()

Message
yes                                                                  6433
no                                                                   2550
Yes                                                                  2033
me                                                                   1210
skillset                                                             1062
                                                                     ...
Soft engg                                                               9
Sir plz stop msgs                                                       8
hi                                                                      8
not audible                                                             8
Now a days I faced mostly are fake job posts how can I overcome i       1
Name: count, Length: 1254, dtype: int64

In [31]:
dm1['Message'].str.contains('linkedin.com').value_counts().get(True)

6591

In [32]:
dm1['Message'].isna().sum()

4614

In [33]:
dm1['Message'] = dm1['Message'].fillna('na')
dm2 = dm1[dm1['Message'].str.contains('linkedin.com')]
dm2

                                                 Message
1368   https://www.linkedin.com/in/aardra-reji-a615ba...
1369                   www.linkedin.com/in/sathish-vanga
1370   https://www.linkedin.com/in/abhishek-ganeshkar...
1371   https://www.linkedin.com/in/vishakha-deshmukh-...
1372   https://www.linkedin.com/in/harsh-raj-gupta-38...
...                                                  ...
44397    https://www.linkedin.com/in/raj-kumarsaggurthi/
44413        https://www.linkedin.com/in/aminat-owodunni
44538  https://www.linkedin.com/in/mudassir-ahmed2?ut...
44596  https://www.linkedin.com/feed/hashtag/datascie...
44742  https://www.linkedin.com/in/kavinpuri/     End...

[6591 rows x 1 columns]

In [34]:
dm2['Message'].size

6591

In [35]:
dm3 = dm2[dm2['Message'].str.contains('/feed')]
dm3

                                                 Message
1401                      https://www.linkedin.com/feed/
1415                      https://www.linkedin.com/feed/
1436                      https://www.linkedin.com/feed/
1467                      https://www.linkedin.com/feed/
1601                      https://www.linkedin.com/feed/
...                                                  ...
42820                     https://www.linkedin.com/feed/
42841                     https://www.linkedin.com/feed/
42856                     https://www.linkedin.com/feed/
42870                     https://www.linkedin.com/feed/
44596  https://www.linkedin.com/feed/hashtag/datascie...

[142 rows x 1 columns]

In [36]:
dm4 = dm2[dm2['Message'].str.endswith('/in/')]
dm4.size

45

In [37]:
valid = 6591 - (dm3.size + dm4.size)
valid

6404

In [38]:
dm2['Message'].nunique()

135

In [39]:
df_unique = pd.DataFrame(dm2['Message'].unique())
df_unique

                                                     0
0    https://www.linkedin.com/in/aardra-reji-a615ba...
1                    www.linkedin.com/in/sathish-vanga
2    https://www.linkedin.com/in/abhishek-ganeshkar...
3    https://www.linkedin.com/in/vishakha-deshmukh-...
4    https://www.linkedin.com/in/harsh-raj-gupta-38...
..                                                 ...
130    https://www.linkedin.com/in/raj-kumarsaggurthi/
131        https://www.linkedin.com/in/aminat-owodunni
132  https://www.linkedin.com/in/mudassir-ahmed2?ut...
133  https://www.linkedin.com/feed/hashtag/datascie...
134  https://www.linkedin.com/in/kavinpuri/     End...

[135 rows x 1 columns]

In [40]:
df_feed = df_unique[df_unique[0].str.contains('feed')]
df_feed.size

2

In [41]:
df_in = df_unique[df_unique[0].str.endswith('/in/')]
df_in.size

2

In [42]:
df_valid_in_unique = 135 - (df_feed.size + df_in.size)
df_valid_in_unique

131

In [43]:
misconduct1 = dm1[dm1['Message'].str.contains('zoom')]
misconduct1

                                                 Message
3321   https://us02web.zoom.us/w/82416269753?tk=XAfCC...
5944   https://us02web.zoom.us/w/82416269753?tk=XAfCC...
9836   https://us02web.zoom.us/w/82416269753?tk=XAfCC...
13513  https://us02web.zoom.us/w/82416269753?tk=XAfCC...
14701  https://us02web.zoom.us/w/82416269753?tk=XAfCC...
20776  https://us02web.zoom.us/w/82416269753?tk=XAfCC...
24153  https://us02web.zoom.us/w/82416269753?tk=XAfCC...
28072  https://us02web.zoom.us/w/82416269753?tk=XAfCC...
36785  https://us02web.zoom.us/w/82416269753?tk=XAfCC...
38517  https://us02web.zoom.us/w/82416269753?tk=XAfCC...
42423  https://us02web.zoom.us/w/82416269753?tk=XAfCC...
44446  https://us02web.zoom.us/w/82416269753?tk=XAfCC...

In [44]:
misconduct1['Message'].nunique()

1